# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.paginator:
            class: AppBundle\Services\Paginator

    app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }

    app.password_listener:
            class: AppBundle\EventListener\PasswordListener
            arguments: ["@security.encoder_factory"]
            tags:
                - { name: doctrine.event_listener, event: prePersist }